version: '2.1'
services:
  app:
    build: .
    image: queens-app
    container_name: nqueens-app
    volumes:
    - ./src:/src
    depends_on:
      db:
        condition: service_healthy
    command: ['wait-for-it.sh', 'db:5432', '--', 'python3','queens.py']
  db:
    image: mdillon/postgis
    container_name: queen-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: nqueen-db
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5